name: contexts
run-name: Contexts info

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DAY: Wednesday

jobs:
    github_context:
        runs-on: ubuntu-latest
        steps:
            - name: github
              run: echo "Hi ${{ github.actor }} you are working on ${{ github.repository }}, in the branch ${{ github.ref }} triggerred by a ${{ github.event_name}}"  

    runner_context:
        runs-on: ubuntu-latest
        steps:
          - name: runner
            run: echo "Hi ${{ runner.os }} runner, you are running on ${{ runner.arch }} architecture"

    env_context:
        runs-on: ubuntu-latest
        steps:
          - name: env
            run: echo "Today is ${{ env.DAY }}"
    
    step_context:
      runs-on: ubuntu-latest
      steps:
        - name: hello
          id: hello
          run: echo "My name is ${{ github.actor }}" >> "$GITHUB_OUTPUT"

        - name: output
          run: echo "Output ${{ steps.hello.outputs.result }}"
        
    
    