name: hello-world
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'
      - name: hello-world
        run: go run main.go
